import * as dotenv from 'dotenv';

dotenv.config();
export const configs =
  process.env.ENVIRONMENT == 'development'
    ? {
        BASE_URL: process.env.DEV_BASE_URL as string,
        ENVIRONMENT: process.env.ENVIRONMENT,
        MONGO_DB_URL: process.env.DEV_MONGO_URI as string,
        JWT_SECRET: process.env.DEV_JWT_SECRET as string,
        JWT_FORGOTPASSWORD_SECRET: process.env
          .DEV_FORGOTPASSWORD_JWT_SECRET as string,
        JWT_AGENT_SECRET: process.env.DEV_AGENT_JWT_SECRET as string,
        JWT_EXIPIRY: process.env.DEV_JWT_EXPIRY as string,
        EMAIL_JWT_SECRET: process.env.EMAIL_JWT_EXPIRY as string,
        EMAIL_JWT_EXPIRY: process.env.EMAIL_JWT_EXPIRY as string,
        EMAIL_SERVICE: process.env.DEV_NODEMAILER_EMAIL_SERVICE as string,
        EMAIL_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER as string,
        EMAIL_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD as string,
        EMAIL_HOST: process.env.DEV_NODEMAILER_HOST as string,
        EMAIL_PORT: process.env.DEV_NODEMAILER_PORT as string,
        EMAIL_FROM: process.env.PRODUCTION_EMAIL_FROM as string,
        TWILO_SID: process.env.DEV_TWILO_SID as string,
        TWILO_AUTH_TOKEN: process.env.DEV_TWILO_AUTH_TOKEN as string,
        TWILO_PHONE_NUMBER: process.env.DEV_TWILO_PHONE_NUMBER as string,
        TWILO_PHONE_NUMBER_SID: process.env.DEV_TWILO_PHONE_NUMBER_SID,
        BUCKET_NAME: process.env.BUCKET_NAME as string,
        MAILER_HOST: process.env.MAILER_HOST as string,
        MAILER_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER as string,
        MAILER_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD as string,
        MAILER_PORT: process.env.MAILER_PORT as string,
        EMAIL_LOGIN_URL: process.env.MAILER_PORT || 'https://login.com',
        STRIPE_PUB_KEY: process.env.DEV_STRIPE_PUB_KEY as string,
        STRIPE_SECRET_KEY: process.env.DEV_STRIPE_SECRET_KEY as string,
        STRIPE_WEBHOOK_SECRET: process.env.DEV_STRIPE_WEBHOOK_SECRET as string,
        ADMIN_API_KEY: process.env.DEV_ADMIN_API_KEY as string,
        DATA_INFINITI_API_KEY: process.env.DEV_DATA_INFINITI_KEY as string,
        MLS_API_AUTH_KEY: process.env.MLS_API_AUTH_KEY as string,
        MLS_CLIENT_ID: process.env.MLS_CLIENT_ID as string,
        MLS_CLIENT_SECRET: process.env.MLS_CLIENT_SECRET as string,
        MLS_RAPID_API_KEY: process.env.MLS_RAPID_API_KEY as string,
        MLS_X_API_REQUEST_KEY: process.env.MLS_X_API_REQUEST_KEY as string,
        MLS__RAPID_API_REQUEST_KEY: process.env
          .MLS__RAPID_API_REQUEST_KEY as string,
        MLS__RAPID_API_REQUEST_HOST: process.env
          .MLS__RAPID_API_REQUEST_HOST as string,
        S3_BUCKET_NAME: process.env.S3_BUCKET_NAME as string,
        AMAZON_SES_SMTP_ENDPOINT: process.env
          .AMAZON_SES_SMTP_ENDPOINT as string,
        ACCESS_AWS_KEY: process.env.ACCESS_AWS_KEY as string,
        SECRET_AWS__ACCESS_KEY: process.env.SECRET_AWS__ACCESS_KEY as string,
        AMAZON_SES_USERNAME: process.env.AMAZON_SES_USERNAME as string,
        AMAZON_SES_PASSWORD: process.env.AMAZON_SES_PASSWORD as string,
        AWS_REGION: process.env.AWS_REGION as string,
        DOCUSIGN_USER_ID: process.env.DOCUSIGN_USER_ID as string,
        DOCUSIGN_CLIENT_SECRET: process.env.DOCUSIGN_CLIENT_SECRET as string,
        DOCUSIGN_USERNAME: process.env.DOCUSIGN_USERNAME as string,
        DOCUSIGN_PASSWORD: process.env.DOCUSIGN_PASSWORD as string,
        DOCUSIGN_ACCOUNT_ID: process.env.DOCUSIGN_ACCOUNT_ID as string,
        DOCUSIGN_PRIVATE_KEY: process.env.DOCUSIGN_PRIVATE_KEY as string,
        DOCUSIGN_INTEGRATOR_KEY: process.env.DOCUSIGN_INTEGRATOR_KEY as string,
        DOCUSIGN_BASE_PATH: process.env.DOCUSIGN_BASE_PATH as string,
        DOCUSIGN_OAUTH_URL: process.env.DOCUSIGN_OAUTH_URL as string,
        DOCUSIGN_REDIRECT_URI: process.env.DOCUSIGN_REDIRECT_URI as string,
        DOCUSIGN_RSA_KEY_ID: process.env.DOCUSIGN_RSA_KEY_ID as string,
        DOCUSIGN_PUBLIC_KEY: process.env.DOCUSIGN_PUBLIC_KEY as string,
        SELF_BASE_URL: process.env.DEV_SELF_BASE_URL,
        GOOGLE_AUTH_CLIENT_ID: process.env.DEV_GOOGLE_AUTH_CLIENT_ID,
        GOOGLE_AUTH_CLIENT_SECRET: process.env.DEV_GOOGLE_AUTH_CLIENT_SECRET,
        FACEBOOK_AUTH_APP_ID: process.env.DEV_FACEBOOK_AUTH_APP_ID,
        FACEBOOK_AUTH_APP_SECRET: process.env.DEV_FACEBOOK_AUTH_APP_SECRET,
        oneSignal_api_key: process.env.DEV_ONESIGNAL_API_KEY,
        oneSignal_app_id: process.env.ONESIGNAL_APP_ID,
        data_infinite_api_token: process.env.DATAINIFINITI_API_TOKEN,
        google_redirect_url: process.env.DEV_GOOGLE_REDIRECT_URL,
      }
    : process.env.ENVIRONMENT == 'production'
      ? {
          BASE_URL: process.env.PRODUCTION_BASE_URL as string,
          ENVIRONMENT: process.env.ENVIRONMENT,
          MONGO_DB_URL: process.env.DEV_MONGO_URI as string,
          JWT_AGENT_SECRET: process.env.PROD_AGENT_JWT_SECRET as string,
          JWT_SECRET: process.env.PROD_JWT_SECRET as string,
          JWT_FORGOTPASSWORD_SECRET: process.env
            .PROD_FORGOTPASSWORD_JWT_SECRET as string,
          EMAIL_JWT_SECRET: process.env.EMAIL_JWT_EXPIRY as string,
          EMAIL_JWT_EXPIRY: process.env.EMAIL_JWT_EXPIRY as string,
          JWT_EXIPIRY: process.env.PROD_JWT_EXPIRY as string,
          EMAIL_SERVICE: process.env
            .PRODUCTION_NODEMAILER_EMAIL_SERVICE as string,
          EMAIL_USERNAME: process.env
            .PRODUCTION_NODEMAILER_EMAIL_USER as string,
          EMAIL_PASSWORD: process.env
            .PRODUCTION_NODEMAILER_EMAIL_PASSWORD as string,
          EMAIL_HOST: process.env.PRODUCTION_NODEMAILER_HOST as string,
          EMAIL_PORT: process.env.PRODUCTION_NODEMAILER_PORT as string,
          TWILO_SID: process.env.PRODUCTION_TWILO_SID as string,
          TWILO_AUTH_TOKEN: process.env.PRODUCTION_TWILO_AUTH_TOKEN as string,
          TWILO_PHONE_NUMBER: process.env
            .PRODUCTION_TWILO_PHONE_NUMBER as string,
          TWILO_PHONE_NUMBER_SID: process.env
            .PRODUCTION_TWILO_PHONE_NUMBER_SID as string,
          BUCKET_NAME: process.env.BUCKET_NAME as string,
          MAILER_HOST: process.env.MAILER_HOST as string,
          MAILER_USERNAME: process.env.PROD_NODEMAILER_EMAIL_USER as string,
          MAILER_PASSWORD: process.env.PROD_NODEMAILER_EMAIL_PASSWORD as string,
          MAILER_PORT: process.env.MAILER_PORT as string,
          EMAIL_LOGIN_URL: process.env.MAILER_PORT || 'https://login.com',
          STRIPE_PUB_KEY: process.env.PROD_STRIPE_PUB_KEY as string,
          STRIPE_SECRET_KEY: process.env.PROD_STRIPE_SECRET_KEY as string,
          STRIPE_WEBHOOK_SECRET: process.env
            .PROD_STRIPE_WEBHOOK_SECRET as string,
          ADMIN_API_KEY: process.env.PROD_ADMIN_API_KEY as string,
          DATA_INFINITI_API_KEY: process.env.PROD_DATA_INFINITI_KEY as string,
          MLS_API_AUTH_KEY: process.env.MLS_API_AUTH_KEY as string,
          MLS_CLIENT_ID: process.env.MLS_CLIENT_ID as string,
          MLS_CLIENT_SECRET: process.env.MLS_CLIENT_SECRET as string,
          MLS_RAPID_API_KEY: process.env.MLS_RAPID_API_KEY as string,
          MLS_X_API_REQUEST_KEY: process.env.MLS_X_API_REQUEST_KEY as string,
          MLS__RAPID_API_REQUEST_KEY: process.env
            .MLS__RAPID_API_REQUEST_KEY as string,
          MLS__RAPID_API_REQUEST_HOST: process.env
            .MLS__RAPID_API_REQUEST_HOST as string,
          S3_BUCKET_NAME: process.env.S3_BUCKET_NAME as string,
          AMAZON_SES_SMTP_ENDPOINT: process.env
            .AMAZON_SES_SMTP_ENDPOINT as string,
          ACCESS_AWS_KEY: process.env.ACCESS_AWS_KEY as string,
          SECRET_AWS__ACCESS_KEY: process.env.SECRET_AWS__ACCESS_KEY as string,
          AMAZON_SES_USERNAME: process.env.AMAZON_SES_USERNAME as string,
          AMAZON_SES_PASSWORD: process.env.AMAZON_SES_PASSWORD as string,
          AWS_REGION: process.env.AWS_REGION as string,
          DOCUSIGN_USER_ID: process.env.DOCUSIGN_USER_ID as string,
          DOCUSIGN_CLIENT_SECRET: process.env.DOCUSIGN_CLIENT_SECRET as string,
          DOCUSIGN_USERNAME: process.env.DOCUSIGN_USERNAME as string,
          DOCUSIGN_PASSWORD: process.env.DOCUSIGN_PASSWORD as string,
          DOCUSIGN_ACCOUNT_ID: process.env.DOCUSIGN_ACCOUNT_ID as string,
          DOCUSIGN_PRIVATE_KEY: process.env.DOCUSIGN_PRIVATE_KEY as string,
          DOCUSIGN_INTEGRATOR_KEY: process.env
            .DOCUSIGN_INTEGRATOR_KEY as string,
          DOCUSIGN_BASE_PATH: process.env.DOCUSIGN_BASE_PATH as string,
          DOCUSIGN_OAUTH_URL: process.env.DOCUSIGN_OAUTH_URL as string,
          DOCUSIGN_REDIRECT_URI: process.env.DOCUSIGN_REDIRECT_URI as string,
          DOCUSIGN_RSA_KEY_ID: process.env.DOCUSIGN_RSA_KEY_ID as string,
          DOCUSIGN_PUBLIC_KEY: process.env.DOCUSIGN_PUBLIC_KEY as string,
          SELF_BASE_URL: process.env.PROD_SELF_BASE_URL,
          GOOGLE_AUTH_CLIENT_ID: process.env.PROD_GOOGLE_AUTH_CLIENT_ID,
          GOOGLE_AUTH_CLIENT_SECRET: process.env.PROD_GOOGLE_AUTH_CLIENT_SECRET,
          FACEBOOK_AUTH_APP_ID: process.env.PROD_FACEBOOK_AUTH_APP_ID,
          FACEBOOK_AUTH_APP_SECRET: process.env.PROD_FACEBOOK_AUTH_APP_SECRET,
          oneSignal_api_key: process.env.DEV_ONESIGNAL_API_KEY,
          oneSignal_app_id: process.env.ONESIGNAL_APP_ID,
          data_infinite_api_token: process.env.DATAINIFINITI_API_TOKEN,
          google_redirect_url: process.env.PROD_GOOGLE_REDIRECT_URL,
        }
      : {
          BASE_URL: 'http://localhost:3000',
          ENVIRONMENT: process.env.ENVIRONMENT,
          MONGO_DB_URL: process.env.DEV_MONGO_URI as string,
          JWT_SECRET: process.env.DEV_JWT_SECRET as string,
          EMAIL_JWT_SECRET: process.env.EMAIL_JWT_EXPIRY as string,
          JWT_AGENT_SECRET: process.env.DEV_AGENT_JWT_SECRET as string,
          JWT_FORGOTPASSWORD_SECRET: process.env
            .DEV_FORGOTPASSWORD_JWT_SECRET as string,
          EMAIL_JWT_EXPIRY: process.env.EMAIL_JWT_EXPIRY as string,
          JWT_EXIPIRY: process.env.DEV_JWT_EXPIRY as string,
          EMAIL_SERVICE: process.env.DEV_NODEMAILER_EMAIL_SERVICE as string,
          EMAIL_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER as string,
          EMAIL_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD as string,
          EMAIL_HOST: process.env.DEV_NODEMAILER_HOST as string,
          EMAIL_PORT: process.env.DEV_NODEMAILER_PORT as string,
          EMAIL_FROM: process.env.PRODUCTION_EMAIL_FROM as string,
          TWILO_SID: process.env.DEV_TWILO_SID as string,
          TWILO_AUTH_TOKEN: process.env.DEV_TWILO_AUTH_TOKEN as string,
          TWILO_PHONE_NUMBER: process.env.DEV_TWILO_PHONE_NUMBER as string,
          TWILO_PHONE_NUMBER_SID: process.env
            .DEV_TWILO_PHONE_NUMBER_SID as string,
          BUCKET_NAME: process.env.BUCKET_NAME as string,
          MAILER_HOST: process.env.MAILER_HOST as string,
          MAILER_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER as string,
          MAILER_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD as string,
          MAILER_PORT: process.env.MAILER_PORT as string,
          EMAIL_LOGIN_URL: process.env.MAILER_PORT || 'https://login.com',
          STRIPE_PUB_KEY: process.env.DEV_STRIPE_PUB_KEY as string,
          STRIPE_SECRET_KEY: process.env.DEV_STRIPE_SECRET_KEY as string,
          STRIPE_WEBHOOK_SECRET: process.env
            .DEV_STRIPE_WEBHOOK_SECRET as string,
          ADMIN_API_KEY: process.env.DEV_ADMIN_API_KEY as string,
          DATA_INFINITI_API_KEY: process.env.DEV_DATA_INFINITI_KEY as string,
          MLS_API_AUTH_KEY: process.env.MLS_API_AUTH_KEY as string,
          MLS_CLIENT_ID: process.env.MLS_CLIENT_ID as string,
          MLS_CLIENT_SECRET: process.env.MLS_CLIENT_SECRET as string,
          MLS_RAPID_API_KEY: process.env.MLS_RAPID_API_KEY as string,
          MLS_X_API_REQUEST_KEY: process.env.MLS_X_API_REQUEST_KEY as string,
          MLS__RAPID_API_REQUEST_KEY: process.env
            .MLS__RAPID_API_REQUEST_KEY as string,
          MLS__RAPID_API_REQUEST_HOST: process.env
            .MLS__RAPID_API_REQUEST_HOST as string,
          S3_BUCKET_NAME: process.env.S3_BUCKET_NAME as string,
          AMAZON_SES_SMTP_ENDPOINT: process.env
            .AMAZON_SES_SMTP_ENDPOINT as string,
          ACCESS_AWS_KEY: process.env.ACCESS_AWS_KEY as string,
          SECRET_AWS__ACCESS_KEY: process.env.SECRET_AWS__ACCESS_KEY as string,
          AMAZON_SES_USERNAME: process.env.AMAZON_SES_USERNAME as string,
          AMAZON_SES_PASSWORD: process.env.AMAZON_SES_PASSWORD as string,
          AWS_REGION: process.env.AWS_REGION as string,
          DOCUSIGN_USER_ID: process.env.DOCUSIGN_USER_ID as string,
          DOCUSIGN_CLIENT_SECRET: process.env.DOCUSIGN_CLIENT_SECRET as string,
          DOCUSIGN_USERNAME: process.env.DOCUSIGN_USERNAME as string,
          DOCUSIGN_PASSWORD: process.env.DOCUSIGN_PASSWORD as string,
          DOCUSIGN_ACCOUNT_ID: process.env.DOCUSIGN_ACCOUNT_ID as string,
          DOCUSIGN_PRIVATE_KEY: process.env.DOCUSIGN_PRIVATE_KEY as string,
          DOCUSIGN_INTEGRATOR_KEY: process.env
            .DOCUSIGN_INTEGRATOR_KEY as string,
          DOCUSIGN_BASE_PATH: process.env.DOCUSIGN_BASE_PATH as string,
          DOCUSIGN_OAUTH_URL: process.env.DOCUSIGN_OAUTH_URL as string,
          DOCUSIGN_REDIRECT_URI: process.env.DOCUSIGN_REDIRECT_URI as string,
          DOCUSIGN_RSA_KEY_ID: process.env.DOCUSIGN_RSA_KEY_ID as string,
          DOCUSIGN_PUBLIC_KEY: process.env.DOCUSIGN_PUBLIC_KEY as string,
          SELF_BASE_URL: process.env.LOCAL_SELF_BASE_URL,
          GOOGLE_AUTH_CLIENT_ID: process.env.DEV_GOOGLE_AUTH_CLIENT_ID,
          GOOGLE_AUTH_CLIENT_SECRET: process.env.DEV_GOOGLE_AUTH_CLIENT_SECRET,
          FACEBOOK_AUTH_APP_ID: process.env.DEV_FACEBOOK_AUTH_APP_ID,
          FACEBOOK_AUTH_APP_SECRET: process.env.DEV_FACEBOOK_AUTH_APP_SECRET,
          oneSignal_api_key: process.env.DEV_ONESIGNAL_API_KEY,
          oneSignal_app_id: process.env.ONESIGNAL_APP_ID,
          data_infinite_api_token: process.env.DATAINIFINITI_API_TOKEN,
          google_redirect_url: process.env.LOCAL_GOOGLE_REDIRECT_URL,
        };
