import * as dotenv from 'dotenv';

dotenv.config();
export const configs =
  process.env.NODE_ENV == 'development'
    ? {
        BASE_URL: process.env.DEV_BASE_URL || '',
        ENVIRONMENT: process.env.ENVIRONMENT,
        MONGO_DB_URL: process.env.DEV_MONGO_URI || '',
        JWT_SECRET: process.env.DEV_JWT_SECRET || '',
        JWT_FORGOTPASSWORD_SECRET:
          process.env.DEV_FORGOTPASSWORD_JWT_SECRET || '',
        JWT_AGENT_SECRET: process.env.DEV_AGENT_JWT_SECRET || '',
        JWT_EXIPIRY: process.env.DEV_JWT_EXPIRY || '',
        EMAIL_JWT_SECRET: process.env.EMAIL_JWT_EXPIRY || '',
        EMAIL_JWT_EXPIRY: process.env.EMAIL_JWT_EXPIRY || '',
        EMAIL_SERVICE: process.env.DEV_NODEMAILER_EMAIL_SERVICE || '',
        EMAIL_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER || '',
        EMAIL_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD || '',
        EMAIL_HOST: process.env.DEV_NODEMAILER_HOST || '',
        EMAIL_PORT: process.env.DEV_NODEMAILER_PORT || '',
        EMAIL_FROM: process.env.PRODUCTION_EMAIL_FROM || '',
        TWILO_SID: process.env.DEV_TWILO_SID || '',
        TWILO_AUTH_TOKEN: process.env.DEV_TWILO_AUTH_TOKEN || '',
        TWILO_PHONE_NUMBER: process.env.DEV_TWILO_PHONE_NUMBER || '',
        TWILO_PHONE_NUMBER_SID: process.env.DEV_TWILO_PHONE_NUMBER_SID || '',
        BUCKET_NAME: process.env.BUCKET_NAME || '',
        MAILER_HOST: process.env.MAILER_HOST || '',
        MAILER_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER || '',
        MAILER_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD || '',
        MAILER_PORT: process.env.MAILER_PORT || '',
        EMAIL_LOGIN_URL: process.env.MAILER_PORT || 'https://login.com',
        STRIPE_PUB_KEY: process.env.DEV_STRIPE_PUB_KEY || '',
        STRIPE_SECRET_KEY: process.env.DEV_STRIPE_SECRET_KEY || '',
        STRIPE_WEBHOOK_SECRET: process.env.DEV_STRIPE_WEBHOOK_SECRET || '',
        ADMIN_API_KEY: process.env.DEV_ADMIN_API_KEY || '',
        DATA_INFINITI_API_KEY: process.env.DEV_DATA_INFINITI_KEY || '',
        MLS_API_AUTH_KEY: process.env.MLS_API_AUTH_KEY || '',
        MLS_CLIENT_ID: process.env.MLS_CLIENT_ID || '',
        MLS_CLIENT_SECRET: process.env.MLS_CLIENT_SECRET || '',
        MLS_RAPID_API_KEY: process.env.MLS_RAPID_API_KEY || '',
        MLS_X_API_REQUEST_KEY: process.env.MLS_X_API_REQUEST_KEY || '',
        MLS__RAPID_API_REQUEST_KEY:
          process.env.MLS__RAPID_API_REQUEST_KEY || '',
        MLS__RAPID_API_REQUEST_HOST:
          process.env.MLS__RAPID_API_REQUEST_HOST || '',
        S3_BUCKET_NAME: process.env.S3_BUCKET_NAME || '',
      }
    : process.env.ENVIRONMENT == 'production'
      ? {
          BASE_URL: process.env.PRODUCTION_BASE_URL || '',
          ENVIRONMENT: process.env.ENVIRONMENT,
          MONGO_DB_URL: process.env.DEV_MONGO_URI || '',
          JWT_AGENT_SECRET: process.env.PROD_AGENT_JWT_SECRET || '',
          JWT_SECRET: process.env.PROD_JWT_SECRET || '',
          JWT_FORGOTPASSWORD_SECRET:
            process.env.PROD_FORGOTPASSWORD_JWT_SECRET || '',
          EMAIL_JWT_SECRET: process.env.EMAIL_JWT_EXPIRY || '',
          EMAIL_JWT_EXPIRY: process.env.EMAIL_JWT_EXPIRY || '',
          JWT_EXIPIRY: process.env.PROD_JWT_EXPIRY || '',
          EMAIL_SERVICE: process.env.PRODUCTION_NODEMAILER_EMAIL_SERVICE || '',
          EMAIL_USERNAME: process.env.PRODUCTION_NODEMAILER_EMAIL_USER || '',
          EMAIL_PASSWORD:
            process.env.PRODUCTION_NODEMAILER_EMAIL_PASSWORD || '',
          EMAIL_HOST: process.env.PRODUCTION_NODEMAILER_HOST || '',
          EMAIL_PORT: process.env.PRODUCTION_NODEMAILER_PORT || '',
          TWILO_SID: process.env.PRODUCTION_TWILO_SID || '',
          TWILO_AUTH_TOKEN: process.env.PRODUCTION_TWILO_AUTH_TOKEN || '',
          TWILO_PHONE_NUMBER: process.env.PRODUCTION_TWILO_PHONE_NUMBER || '',
          TWILO_PHONE_NUMBER_SID:
            process.env.PRODUCTION_TWILO_PHONE_NUMBER_SID || '',
          BUCKET_NAME: process.env.BUCKET_NAME || '',
          MAILER_HOST: process.env.MAILER_HOST || '',
          MAILER_USERNAME: process.env.PROD_NODEMAILER_EMAIL_USER || '',
          MAILER_PASSWORD: process.env.PROD_NODEMAILER_EMAIL_PASSWORD || '',
          MAILER_PORT: process.env.MAILER_PORT || '',
          EMAIL_LOGIN_URL: process.env.MAILER_PORT || 'https://login.com',
          STRIPE_PUB_KEY: process.env.PROD_STRIPE_PUB_KEY || '',
          STRIPE_SECRET_KEY: process.env.PROD_STRIPE_SECRET_KEY || '',
          STRIPE_WEBHOOK_SECRET: process.env.PROD_STRIPE_WEBHOOK_SECRET || '',
          ADMIN_API_KEY: process.env.PROD_ADMIN_API_KEY || '',
          DATA_INFINITI_API_KEY: process.env.PROD_DATA_INFINITI_KEY || '',
          MLS_API_AUTH_KEY: process.env.MLS_API_AUTH_KEY || '',
          MLS_CLIENT_ID: process.env.MLS_CLIENT_ID || '',
          MLS_CLIENT_SECRET: process.env.MLS_CLIENT_SECRET || '',
          MLS_RAPID_API_KEY: process.env.MLS_RAPID_API_KEY || '',
          MLS_X_API_REQUEST_KEY: process.env.MLS_X_API_REQUEST_KEY || '',
          MLS__RAPID_API_REQUEST_KEY:
            process.env.MLS__RAPID_API_REQUEST_KEY || '',
          MLS__RAPID_API_REQUEST_HOST:
            process.env.MLS__RAPID_API_REQUEST_HOST || '',
          S3_BUCKET_NAME: process.env.S3_BUCKET_NAME || '',
        }
      : {
          BASE_URL: 'http://http://localhost:3000',
          ENVIRONMENT: process.env.ENVIRONMENT,
          MONGO_DB_URL: process.env.DEV_MONGO_URI || '',
          JWT_SECRET: process.env.DEV_JWT_SECRET || '',
          EMAIL_JWT_SECRET: process.env.EMAIL_JWT_EXPIRY || '',
          JWT_AGENT_SECRET: process.env.DEV_AGENT_JWT_SECRET || '',
          JWT_FORGOTPASSWORD_SECRET:
            process.env.DEV_FORGOTPASSWORD_JWT_SECRET || '',
          EMAIL_JWT_EXPIRY: process.env.EMAIL_JWT_EXPIRY || '',
          JWT_EXIPIRY: process.env.DEV_JWT_EXPIRY || '',
          EMAIL_SERVICE: process.env.DEV_NODEMAILER_EMAIL_SERVICE || '',
          EMAIL_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER || '',
          EMAIL_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD || '',
          EMAIL_HOST: process.env.DEV_NODEMAILER_HOST || '',
          EMAIL_PORT: process.env.DEV_NODEMAILER_PORT || '',
          EMAIL_FROM: process.env.PRODUCTION_EMAIL_FROM || '',
          TWILO_SID: process.env.DEV_TWILO_SID || '',
          TWILO_AUTH_TOKEN: process.env.DEV_TWILO_AUTH_TOKEN || '',
          TWILO_PHONE_NUMBER: process.env.DEV_TWILO_PHONE_NUMBER || '',
          TWILO_PHONE_NUMBER_SID: process.env.DEV_TWILO_PHONE_NUMBER_SID || '',
          BUCKET_NAME: process.env.BUCKET_NAME || '',
          MAILER_HOST: process.env.MAILER_HOST || '',
          MAILER_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER || '',
          MAILER_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD || '',
          MAILER_PORT: process.env.MAILER_PORT || '',
          EMAIL_LOGIN_URL: process.env.MAILER_PORT || 'https://login.com',
          STRIPE_PUB_KEY: process.env.DEV_STRIPE_PUB_KEY || '',
          STRIPE_SECRET_KEY: process.env.DEV_STRIPE_SECRET_KEY || '',
          STRIPE_WEBHOOK_SECRET: process.env.DEV_STRIPE_WEBHOOK_SECRET || '',
          ADMIN_API_KEY: process.env.DEV_ADMIN_API_KEY || '',
          DATA_INFINITI_API_KEY: process.env.DEV_DATA_INFINITI_KEY || '',
          MLS_API_AUTH_KEY: process.env.MLS_API_AUTH_KEY || '',
          MLS_CLIENT_ID: process.env.MLS_CLIENT_ID || '',
          MLS_CLIENT_SECRET: process.env.MLS_CLIENT_SECRET || '',
          MLS_RAPID_API_KEY: process.env.MLS_RAPID_API_KEY || '',
          MLS_X_API_REQUEST_KEY: process.env.MLS_X_API_REQUEST_KEY || '',
          MLS__RAPID_API_REQUEST_KEY:
            process.env.MLS__RAPID_API_REQUEST_KEY || '',
          MLS__RAPID_API_REQUEST_HOST:
            process.env.MLS__RAPID_API_REQUEST_HOST || '',
          S3_BUCKET_NAME: process.env.S3_BUCKET_NAME || '',
        };
