import * as dotenv from 'dotenv';

dotenv.config();
export const configs =
  process.env.NODE_ENV == 'development'
    ? {
        BASE_URL: process.env.DEV_BASE_URL || '',
        ENVIRONMENT: process.env.ENVIRONMENT,
        MONGO_DB_URL: process.env.DEV_MONGO_URI || '',
        JWT_SECRET: process.env.DEV_JWT_SECRET || '',
        JWT_EXIPIRY: process.env.DEV_JWT_EXPIRY || '',
        EMAIL_JWT_SECRET: process.env.EMAIL_JWT_EXPIRY || '',
        EMAIL_JWT_EXPIRY: process.env.EMAIL_JWT_EXPIRY || '',
        EMAIL_SERVICE: process.env.DEV_NODEMAILER_EMAIL_SERVICE || '',
        EMAIL_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER || '',
        EMAIL_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD || '',
        EMAIL_HOST: process.env.DEV_NODEMAILER_HOST || '',
        EMAIL_PORT: process.env.DEV_NODEMAILER_PORT || '',
        EMAIL_FROM: process.env.PRODUCTION_EMAIL_FROM || '',
        TWILO_SID: process.env.DEV_TWILO_SID || '',
        TWILO_AUTH_TOKEN: process.env.DEV_TWILO_AUTH_TOKEN || '',
        TWILO_PHONE_NUMBER: process.env.DEV_TWILO_PHONE_NUMBER || '',
        TWILO_PHONE_NUMBER_SID: process.env.DEV_TWILO_PHONE_NUMBER_SID || '',
        BUCKET_NAME: process.env.BUCKET_NAME || '',
        MAILER_HOST: process.env.MAILER_HOST || '',
        MAILER_USERNAME: process.env.MAILER_USERNAME || '',
        MAILER_PASSWORD: process.env.MAILER_PASSWORD || '',
        MAILER_PORT: process.env.MAILER_PORT || '',
        EMAIL_LOGIN_URL: process.env.MAILER_PORT || 'https://login.com',
      }
    : process.env.ENVIRONMENT == 'production'
      ? {
          BASE_URL: process.env.PRODUCTION_BASE_URL || '',
          ENVIRONMENT: process.env.ENVIRONMENT,
          MONGO_DB_URL: process.env.DEV_MONGO_URI || '',
          JWT_SECRET: process.env.PROD_JWT_SECRET || '',
          EMAIL_JWT_SECRET: process.env.EMAIL_JWT_EXPIRY || '',
          EMAIL_JWT_EXPIRY: process.env.EMAIL_JWT_EXPIRY || '',
          JWT_EXIPIRY: process.env.PROD_JWT_EXPIRY || '',
          EMAIL_SERVICE: process.env.PRODUCTION_NODEMAILER_EMAIL_SERVICE || '',
          EMAIL_USERNAME: process.env.PRODUCTION_NODEMAILER_EMAIL_USER || '',
          EMAIL_PASSWORD:
            process.env.PRODUCTION_NODEMAILER_EMAIL_PASSWORD || '',
          EMAIL_HOST: process.env.PRODUCTION_NODEMAILER_HOST || '',
          EMAIL_PORT: process.env.PRODUCTION_NODEMAILER_PORT || '',
          TWILO_SID: process.env.PRODUCTION_TWILO_SID || '',
          TWILO_AUTH_TOKEN: process.env.PRODUCTION_TWILO_AUTH_TOKEN || '',
          TWILO_PHONE_NUMBER: process.env.PRODUCTION_TWILO_PHONE_NUMBER || '',
          TWILO_PHONE_NUMBER_SID:
            process.env.PRODUCTION_TWILO_PHONE_NUMBER_SID || '',
          BUCKET_NAME: process.env.BUCKET_NAME || '',
          MAILER_HOST: process.env.MAILER_HOST || '',
          MAILER_USERNAME: process.env.MAILER_USERNAME || '',
          MAILER_PASSWORD: process.env.MAILER_PASSWORD || '',
          MAILER_PORT: process.env.MAILER_PORT || '',
          EMAIL_LOGIN_URL: process.env.MAILER_PORT || 'https://login.com',
        }
      : {
          BASE_URL: 'http://http://localhost:3000',
          ENVIRONMENT: process.env.ENVIRONMENT,
          MONGO_DB_URL: process.env.DEV_MONGO_URI || '',
          JWT_SECRET: process.env.DEV_JWT_SECRET || '',
          EMAIL_JWT_SECRET: process.env.EMAIL_JWT_EXPIRY || '',
          EMAIL_JWT_EXPIRY: process.env.EMAIL_JWT_EXPIRY || '',
          JWT_EXIPIRY: process.env.DEV_JWT_EXPIRY || '',
          EMAIL_SERVICE: process.env.DEV_NODEMAILER_EMAIL_SERVICE || '',
          EMAIL_USERNAME: process.env.DEV_NODEMAILER_EMAIL_USER || '',
          EMAIL_PASSWORD: process.env.DEV_NODEMAILER_EMAIL_PASSWORD || '',
          EMAIL_HOST: process.env.DEV_NODEMAILER_HOST || '',
          EMAIL_PORT: process.env.DEV_NODEMAILER_PORT || '',
          EMAIL_FROM: process.env.PRODUCTION_EMAIL_FROM || '',
          TWILO_SID: process.env.DEV_TWILO_SID || '',
          TWILO_AUTH_TOKEN: process.env.DEV_TWILO_AUTH_TOKEN || '',
          TWILO_PHONE_NUMBER: process.env.DEV_TWILO_PHONE_NUMBER || '',
          TWILO_PHONE_NUMBER_SID: process.env.DEV_TWILO_PHONE_NUMBER_SID || '',
          BUCKET_NAME: process.env.BUCKET_NAME || '',
          MAILER_HOST: process.env.MAILER_HOST || '',
          MAILER_USERNAME: process.env.MAILER_USERNAME || '',
          MAILER_PASSWORD: process.env.MAILER_PASSWORD || '',
          MAILER_PORT: process.env.MAILER_PORT || '',
          EMAIL_LOGIN_URL: process.env.MAILER_PORT || 'https://login.com',
        };
